### ISSUE TITLE
Missing support for "Rule" keyword

### ISSUE THREAD

**Issue by dpresiana** [Vitalizzzer/cucumber-json-report-formatter#19]
Description
===========
Using "Rule" keyword on cucumber scenarios seems to error out the formatter. 
<img width="278" alt="Screenshot 2023-02-21 at 18 35 51" src="https://user-images.githubusercontent.com/77797592/220405070-18613fd9-0ab9-441d-bd6f-81dbefaa2bc0.png">

Error
=======
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'steps' of undefined
    at */node_modules/cucumber-json-report-formatter/lib/formatter.js:38:38
    at Array.forEach (<anonymous>)
    at */node_modules/cucumber-json-report-formatter/lib/formatter.js:33:23
    at Array.forEach (<anonymous>)
    at Formatter.parseCucumberJson (*/node_modules/cucumber-json-report-formatter/lib/formatter.js:20:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Versions
==========
- "cucumber-json-report-formatter": "0.1.4"

Here is an example `cucumber-messages.ndjson` file:

[cucumber-messages.ndjson.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/10795791/cucumber-messages.ndjson.zip)

**Comment by stanlee974** [comment]
Hi ! 
I push a correction for interpretation of cucumber rule keyword.
until it's validated, you can create a class that extends Formatter and override the parseCucumberJson method to integrate the modification.
